---
- name: Install required package
  yum:
    name: python3-passlib
    state: present
  become: true

- name: Create htpasswd file with defined users
  htpasswd:
    path: "{{ playbook_dir }}/../ocp4-htpasswd"
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    mode: 0644
  loop: "{{ users }}"
