---
- name: Install required package
  yum:
    name: python3-passlib
    state: present

- name: Create htpasswd file with admin user
  htpasswd:
    path: "{{ playbook_dir }}/../ocp4-htpasswd"
    name: "{{ k8s_username }}"
    password: "{{ k8s_password }}"
    mode: 0644
